CREATE TABLE consertos
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_de_entrada  TIMESTAMP,
    data_de_saida    TIMESTAMP,
    email            VARCHAR(255),
    nome             VARCHAR(255),
    anos_experiencia INT                                     NOT NULL,
    marca            VARCHAR(255),
    modelo           VARCHAR(255),
    ano              INT                                     NOT NULL,
    CONSTRAINT pk_consertos PRIMARY KEY (id)
);